import type { Metadata } from 'next'
import { Lato } from 'next/font/google'
import './globals.css'
import DashboardWrapper from './dashboardWrapper'

const lato = Lato({ subsets: ['latin'], weight: ['400', '700'] })

export const metadata: Metadata = {
	title: 'Inventory',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={lato.className}>
				<DashboardWrapper>{children}</DashboardWrapper>
			</body>
		</html>
	)
}
